services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Slub\LisztWeb\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

#  Slub\LisztWeb\EventListener\ForceUidsOnImport:
#    tags: { name: event.listener }
